flowchart TD
    V[View - Swing forme i paneli]
    C[Controller - GUI događaji]
    S[Service - poslovna pravila i transakcije]
    D[Domain - entiteti i Strategy]
    R[Repository DAO - JPA upiti]
    J[EntityManager / Hibernate]
    DB[(Azure SQL Database)]

    V --> C
    C --> S
    S --> D
    S --> R
    R --> J
    J --> DB
